import React from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Sparkles, Activity, ShieldCheck, Zap, Upload, Search, BarChart3, ChevronRight, Heart } from 'lucide-react';
import Button from '../components/Button';
import Card from '../components/Card';
import { useScan } from '../context/ScanContext';

export default function LandingPage() {
  const navigate = useNavigate();
  const { country } = useScan();

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15
      }
    }
  };

  const itemVariants = {
    hidden: { y: 25, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { duration: 0.5, ease: 'easeOut' } }
  };

  const features = [
    {
      icon: <Activity className="w-6 h-6 text-brand-500" />,
      title: 'CNN-Powered Detection',
      desc: 'Trained on tens of thousands of clinical dermascopy images to extract accurate visual lesion biomarkers.'
    },
    {
      icon: <Zap className="w-6 h-6 text-medgreen-500" />,
      title: 'Instant AI Insights',
      desc: 'Processing completes in less than 4 seconds. Get immediate probability percentages for common skin concerns.'
    },
    {
      icon: <ShieldCheck className="w-6 h-6 text-brand-500" />,
      title: 'Private & Secure',
      desc: 'All uploads are processed using encrypted pipelines and conform to medical compliance standards.'
    }
  ];

  const steps = [
    {
      num: '01',
      icon: <Upload className="w-5 h-5 text-brand-500" />,
      title: 'Upload Image',
      desc: 'Take a clear, centered, and well-lit photo of the affected skin area.'
    },
    {
      num: '02',
      icon: <Search className="w-5 h-5 text-medgreen-500" />,
      title: 'AI Analysis',
      desc: 'Our neural network detects boundaries, color distribution, and structural irregularity.'
    },
    {
      num: '03',
      icon: <BarChart3 className="w-5 h-5 text-brand-500" />,
      title: 'Get Results',
      desc: 'Receive a report with confidence scores, explanations, and advice on doctor consults.'
    }
  ];

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="flex flex-col min-h-[80vh]"
    >
      {/* Hero Section */}
      <section className="relative overflow-hidden py-16 md:py-24 bg-white">
        <div className="absolute inset-0 bg-slate-50/50 pointer-events-none" />
        {/* Soft decorative blur */}
        <div className="absolute top-1/4 right-10 w-80 h-80 rounded-full bg-brand-200/20 blur-3xl pointer-events-none" />
        <div className="absolute bottom-1/4 left-10 w-80 h-80 rounded-full bg-medgreen-200/20 blur-3xl pointer-events-none" />

        <div className="container mx-auto px-4 md:px-6 relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            
            {/* Left Column: Text Content */}
            <div className="lg:col-span-7 flex flex-col gap-6 text-center lg:text-left">
              <motion.div variants={itemVariants} className="inline-flex self-center lg:self-start items-center gap-1.5 px-3 py-1 rounded-full border border-brand-100 bg-brand-50/50 text-brand-700 text-xs font-semibold">
                <Sparkles className="w-3.5 h-3.5" />
                Optimized for users in {country}
              </motion.div>

              <motion.h1 variants={itemVariants} className="text-4xl md:text-5xl lg:text-6xl font-extrabold tracking-tight text-slate-800 leading-tight">
                AI Skin Disease <br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-500 to-medgreen-500">
                  Detection System
                </span>
              </motion.h1>

              <motion.p variants={itemVariants} className="text-slate-500 text-base md:text-lg max-w-xl mx-auto lg:mx-0 leading-relaxed">
                Scan your skin concern and get instant, detailed visual diagnostics generated by advanced Deep Learning. Fast, secure, and user-friendly.
              </motion.p>

              <motion.div variants={itemVariants} className="flex flex-col sm:flex-row gap-3 justify-center lg:justify-start pt-2">
                <Button
                  variant="primary"
                  size="lg"
                  iconRight={<ChevronRight className="w-4 h-4" />}
                  onClick={() => navigate('/upload')}
                >
                  Get Started
                </Button>
                <Button
                  variant="outline"
                  size="lg"
                  onClick={() => navigate('/about')}
                >
                  Learn How It Works
                </Button>
              </motion.div>

              {/* Stats badges */}
              <motion.div variants={itemVariants} className="grid grid-cols-3 gap-6 pt-6 border-t border-slate-100 max-w-md mx-auto lg:mx-0">
                <div>
                  <div className="text-2xl font-bold text-slate-800">98.2%</div>
                  <div className="text-[11px] text-slate-400 font-medium uppercase tracking-wider">Top-5 Accuracy</div>
                </div>
                <div>
                  <div className="text-2xl font-bold text-slate-800">150k+</div>
                  <div className="text-[11px] text-slate-400 font-medium uppercase tracking-wider">Scans run</div>
                </div>
                <div>
                  <div className="text-2xl font-bold text-slate-800">&lt;4s</div>
                  <div className="text-[11px] text-slate-400 font-medium uppercase tracking-wider">Analysis Speed</div>
                </div>
              </motion.div>

            </div>

            {/* Right Column: Visual Mockup */}
            <motion.div
              variants={itemVariants}
              className="lg:col-span-5 flex justify-center"
            >
              <div className="relative w-full max-w-[380px]">
                {/* Floating elements */}
                <div className="absolute -top-4 -left-4 bg-white border border-slate-100 rounded-2xl p-3 shadow-apple flex items-center gap-3 z-20 animate-bounce [animation-duration:4s]">
                  <div className="w-8 h-8 rounded-lg bg-medgreen-500 text-white flex items-center justify-center">
                    <Heart className="w-4.5 h-4.5" />
                  </div>
                  <div>
                    <div className="text-xs font-bold text-slate-800">Healthy Skin Scan</div>
                    <div className="text-[10px] text-slate-400">Classified: Benign</div>
                  </div>
                </div>

                {/* Main Image frame */}
                <div className="rounded-[40px] border-8 border-slate-900 bg-slate-900 overflow-hidden shadow-2xl relative aspect-[9/16] w-full">
                  <div className="absolute top-0 inset-x-0 h-6 bg-slate-900 flex justify-center items-center">
                    <div className="w-16 h-4 bg-black rounded-full" />
                  </div>
                  
                  {/* Internal image */}
                  <img
                    src="https://images.unsplash.com/photo-1522337360788-8b13edd793be?w=600&auto=format&fit=crop&q=80"
                    alt="Skin scanning visual simulation"
                    className="w-full h-full object-cover"
                  />
                  
                  {/* Overlaid simulated scanning scanner bar */}
                  <div className="absolute inset-x-0 top-1/3 h-0.5 bg-gradient-to-r from-brand-400 to-medgreen-400 shadow-[0_0_15px_#0ea5e9] animate-[bounce_3s_infinite]" />
                  
                  {/* Screen overlay details */}
                  <div className="absolute bottom-6 left-6 right-6 bg-slate-950/80 backdrop-blur-md rounded-2xl p-4 border border-white/10 text-white">
                    <div className="text-xs font-semibold text-brand-400 uppercase tracking-widest mb-0.5 flex items-center gap-1">
                      <span className="w-1.5 h-1.5 rounded-full bg-brand-400 animate-ping" />
                      Analyzing...
                    </div>
                    <p className="text-sm font-semibold mb-2">Analyzing lesion texture</p>
                    <div className="w-full bg-white/10 rounded-full h-1.5 overflow-hidden">
                      <div className="bg-brand-400 h-full rounded-full w-2/3 animate-pulse" />
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>

          </div>
        </div>
      </section>

      {/* Features Grid Section */}
      <section className="py-20 bg-slate-50/50">
        <div className="container mx-auto px-4 md:px-6">
          <div className="text-center max-w-xl mx-auto mb-16">
            <h2 className="text-3xl font-bold tracking-tight text-slate-800">
              Why use DermaScanAI?
            </h2>
            <p className="text-slate-400 text-sm mt-3">
              We focus on speed, privacy, and clinical-grade visual classification metrics.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {features.map((feat, idx) => (
              <motion.div key={idx} variants={itemVariants}>
                <Card className="h-full border-slate-100 flex flex-col gap-4">
                  <div className="w-12 h-12 rounded-xl bg-slate-50 flex items-center justify-center shadow-sm">
                    {feat.icon}
                  </div>
                  <div>
                    <h3 className="font-semibold text-slate-800 text-lg mb-2">{feat.title}</h3>
                    <p className="text-slate-400 text-xs leading-relaxed">{feat.desc}</p>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How it Works Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 md:px-6">
          <div className="text-center max-w-xl mx-auto mb-16">
            <h2 className="text-3xl font-bold tracking-tight text-slate-800">
              How it works
            </h2>
            <p className="text-slate-400 text-sm mt-3">
              Analyze skin lesions in three simple and quick steps.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-12 relative">
            {/* Connecting visual line for desktop */}
            <div className="hidden md:block absolute top-[64px] left-[15%] right-[15%] h-0.5 border-t border-dashed border-slate-200 z-0" />

            {steps.map((step, idx) => (
              <motion.div key={idx} variants={itemVariants} className="flex flex-col items-center text-center relative z-10">
                <div className="w-14 h-14 rounded-full border border-slate-100 bg-white shadow-apple flex items-center justify-center mb-6 relative">
                  {step.icon}
                  <span className="absolute -top-1 -right-1 bg-slate-900 text-white rounded-full w-5 h-5 text-[10px] font-bold flex items-center justify-center">
                    {step.num}
                  </span>
                </div>
                <h3 className="font-semibold text-slate-800 text-lg mb-2">{step.title}</h3>
                <p className="text-slate-400 text-xs leading-relaxed max-w-xs">{step.desc}</p>
              </motion.div>
            ))}
          </div>

          <div className="mt-16 text-center">
            <Button variant="primary" size="lg" onClick={() => navigate('/upload')}>
              Start Free Scan Now
            </Button>
          </div>
        </div>
      </section>
    </motion.div>
  );
}
